WydatkiDomoweWeb.WebUI/Controllers/CrudBillsNamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WydatkiDomoweWeb.Domain.Abstract;
using WydatkiDomoweWeb.WebUI.Models;
using WydatkiDomoweWeb.Domain.Entities;

namespace WydatkiDomoweWeb.WebUI.Controllers
{
    public class CrudBillsNamesController : Controller
    {
        private IBillRepository billRepository;
        private IBillNameRepository billNameRepository;
        private IRecipientRepository recipientRepository;

        public CrudBillsNamesController(IBillRepository bill, IBillNameRepository billName, IRecipientRepository recipient)
        {
            this.billRepository = bill;
            this.billNameRepository = billName;
            this.recipientRepository = recipient;
        }

        [HttpGet]
        public PartialViewResult AddBillName()
        {
            BillNameViewModel model = new BillNameViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult AddBillName(BillNameViewModel model)
        {
            if (ModelState.IsValid)
            {
                billNameRepository.Add(CreateBillName(model));
                TempData["ChangedBillName"] = string.Format("Zapisano nazwę rachunku: {0} ", model.Name.ToString());
            }

            return RedirectToAction("Index", "BillsNames");
        }

        [HttpGet]
        public PartialViewResult EditBillName(int billNameId)
        {
            BillName billName = billNameRepository.BillNames.Single(bn => bn.BillNameID == billNameId);

            BillNameViewModel model = new BillNameViewModel
            {
                BillNameId = billNameId,
                Name = billName.Name,
                FirstPaymentDate = billName.FirstPaymentDate.ToString("dd.MM.yyyy"),
                PaymentsFerquency = billName.PaymentsFrequency
            };

            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult EditBillName(BillNameViewModel model)
        {
            if (ModelState.IsValid)
            {
                billNameRepository.Update(CreateBillName(model));
                TempData["ChangedBillName"] = string.Format("Zapisano zmiany w nazwie rachunku: {0} ", model.Name);
            }

            return RedirectToAction("Index", "BillsNames");
        }

        [HttpGet]
        public PartialViewResult DeleteBillName(int billNameId)
        {
            ItemDeleteViewModel model = new ItemDeleteViewModel
            {
                Bills = (from b in billRepository.Bills
                         join bn in billNameRepository.BillNames
                            on b.BillNameID equals bn.BillNameID
                         join r in recipientRepository.Recipients
                            on b.RecipientID equals r.RecipientID
                         where b.BillNameID == billNameId
                         select new BillViewModel
                         {
                             BillId = b.BillsID,
                             BillName = bn.Name,
                             Recipient = r.Name,
                             Amount = b.Amount,
                             PaymentDate = b.PaymentDate,
                             RequiredDate = b.RequiredDate
                         }).ToList(),
                 Id = billNameId,
                 Name = billNameRepository.BillNames.Single(bn => bn.BillNameID == billNameId).Name
            };

            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult DeleteBillName(ItemDeleteViewModel model)
        {
            if (model.Bills.Count() != 0)
            {
                foreach (var bill in model.Bills)
                    billRepository.Delete(bill.BillId);
            }

            billNameRepository.Delete(model.Id);
            TempData["ChangedBillName"] = string.Format("Usunięto nazwę rachunku: {0} ", model.Name);
            
            return RedirectToAction("GetBillsNames", "BillsNames");
        }

        public JsonResult ValidateName(string name, int BillNameId)
        {
            JsonResult result;

            if (billNameRepository.Exists(name))
            {
                int idByName = billNameRepository.BillNames.Single(bn => bn.Name.ToLower() == name.ToLower()).BillNameID;
                
                if (BillNameId != idByName)
                    result = Json("Wybrana nazwa rachunku już istnieje w bazie danych", JsonRequestBehavior.AllowGet);
                else
                    result = Json(true, JsonRequestBehavior.AllowGet);
            }
            else
                result = Json(true, JsonRequestBehavior.AllowGet);

            return result;
        }

        protected BillName CreateBillName(BillNameViewModel model)
        {
            BillName billName = new BillName
            {
                BillNameID = model.BillNameId,
                Name = model.Name,
                FirstPaymentDate = DateTime.ParseExact(model.FirstPaymentDate, "dd.MM.yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture),
                PaymentsFrequency = model.PaymentsFerquency
            };

            return billName;
        }
    }
}

WydatkiDomoweWeb.WebUI/Views/CrudBillsNames/AddBillName.cshtml
@model WydatkiDomoweWeb.WebUI.Models.BillNameViewModel

@Scripts.Render("~/bundles/validation")

@using (Html.BeginForm("AddBillName", "CrudBillsNames"))
{
    <table class="table table-addItem">
        <tr class="col-md-8">
             <td style="width:130px">
                @Html.HiddenFor(m => m.BillNameId)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Nazwa", maxlength = "15" })
                @Html.ValidationMessageFor(m => m.Name)
            </td>
            <td style="width:130px">
                @Html.TextBoxFor(m => m.FirstPaymentDate, new { @class = "form-control", id = "firstPaymentDate", placeholder = "Pierwsza wpłata" })
                @Html.ValidationMessageFor(m => m.FirstPaymentDate)
            </td>
            <td style="width:130px">
                @Html.TextBoxFor(m => m.PaymentsFerquency, new { @class = "form-control", placeholder = "Częstotliwość", Value = "" })
                @Html.ValidationMessageFor(m => m.PaymentsFerquency)
            </td>
            <td style="width:140px">
                <input class="btn btn-primary" type="submit" value="Zapisz" />
                <input class="btn btn-primary" type="button" value="Anuluj" onclick="undoToDefaultAddItem()" />
            </td>
        </tr>
    </table>  
}

WydatkiDomoweWeb.WebUI/Views/CrudBillsNames/DeleteBillName.cshtml
@model WydatkiDomoweWeb.WebUI.Models.ItemDeleteViewModel

@if (Model.Bills.Count() != 0)
{
    <h4>Pozycje powiązane z nazwą rachunku "@Model.Name" zostaną równeż usunięte z bazy danych.</h4>
    <h4>Chcesz dalej kontynuować?</h4>
    <table class="table table-striped table-condensed table-bordered table-getItem">
        <tr>
            <th class="col-md-2">Rachunek</th>
            <th class="col-md-2">Odbiorca</th>
            <th class="col-md-1">Cena</th>
            <th class="col-md-2">Data wpłaty</th>
            <th class="col-md-2">Termin zapłaty</th>
        </tr>

    @foreach (var bill in Model.Bills)
    {
        <tr>
            <td>@Html.DisplayFor(m => bill.BillName)</td>
            <td>@Html.DisplayFor(m => bill.Recipient)</td>
            <td>@Html.DisplayFor(m => bill.Amount)</td>
            <td>@Html.DisplayFor(m => bill.PaymentDate)</td>
            <td>@Html.DisplayFor(m => bill.RequiredDate)</td>            
        </tr>
    }
     </table>
}
else
{
    <script type="text/javascript">
        $(function () {
            $("#"+ "@Model.Id").addClass("modal-sm").removeClass("modal-lg");
        })
    </script>
    
    <h5>Chcesz usunąc nazwę rachunku "@Model.Name"?</h5>
}
<div class="modal-footer">
    @using (Ajax.BeginForm("DeleteBillName", "CrudBillsNames", null, new AjaxOptions { UpdateTargetId = "billsNamesTable", OnSuccess = "hideModal()" }, new { @class = "form-group" }))
    {
        for (int i = 0; i < Model.Bills.Count(); i++)
        {
            @Html.HiddenFor(m => m.Bills[i].BillId)            
        }
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.Name)

        <input class="btn btn-primary" type="submit" value="Usuń" />
    }
    <button type="button" class="btn btn-default" data-dismiss="modal"> Anuluj</button>
</div>

WydatkiDomoweWeb.WebUI/Views/CrudBillsNames/EditBillName.cshtml
@model WydatkiDomoweWeb.WebUI.Models.BillNameViewModel

@Scripts.Render("~/bundles/validation")

@using (Html.BeginForm("EditBillName", "CrudBillsNames"))
{
    <table class="table table-addItem">
        <tr class="col-md-8">
           <td style="width:130px">
                @Html.HiddenFor(m => m.BillNameId)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Nazwa", maxlength = "15" })
                @Html.ValidationMessageFor(m => m.Name)
            </td>
            <td style="width:130px">
                @Html.TextBoxFor(m => m.FirstPaymentDate, new { @class = "form-control", id = "firstPaymentDate", placeholder = "Pierwsza wpłata" })
                @Html.ValidationMessageFor(m => m.FirstPaymentDate)
            </td>
            <td style="width:130px">
                @Html.TextBoxFor(m => m.PaymentsFerquency, new { @class = "form-control", placeholder = "Częstotliwość" })
                @Html.ValidationMessageFor(m => m.PaymentsFerquency)
            </td>
            <td style="width:140px">
                <input class="btn btn-primary" type="submit" value="Zapisz" />
                <input class="btn btn-primary" type="button" value="Anuluj" onclick="undoToDefaultAddItem()" />
            </td>
        </tr>
    </table>  
}