WydatkiDomoweWeb.WebUI/Models/BillViewModel.cs
using WydatkiDomoweWeb.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WydatkiDomoweWeb.WebUI.Models
{
    public class BillModel
    {
        public int Id { get; set; }
        public string BillName { get; set; }
        public string Recipient { get; set; }

        [DisplayFormat(DataFormatString = "{0:c2}")]
        public decimal Amount { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [DataType(DataType.Date)]
        public DateTime PaymentDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [DataType(DataType.Date)]
        public DateTime RequiredDate { get; set; }
    }

    public class BillViewModel
    {
        public IEnumerable<BillModel> Bills { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

WydatkiDomoweWeb.WebUI/Models/BillsViewModel.cs
using WydatkiDomoweWeb.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WydatkiDomoweWeb.WebUI.Models
{
    public class BillViewModel
    {
        public int BillId { get; set; }
        public string BillName { get; set; }
        public string Recipient { get; set; }

        [DisplayFormat(DataFormatString = "{0:c2}")]
        public decimal Amount { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [DataType(DataType.Date)]
        public DateTime PaymentDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        [DataType(DataType.Date)]
        public DateTime RequiredDate { get; set; }
    }

    public class BillsViewModel
    {
        public IEnumerable<BillViewModel> Bills { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

WydatkiDomoweWeb.WebUI/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WydatkiDomoweWeb.WebUI.Models;
using WydatkiDomoweWeb.Domain.Abstract;
using WydatkiDomoweWeb.Domain.Entities;

namespace WydatkiDomoweWeb.WebUI.Controllers
{
    public class BillController : Controller
    {
        private IBillRepository billRepository;
        private IBillNameRepository billNameRepository;
        private IRecipientRepository recipientRepository;

        public BillController(IBillRepository bill, IBillNameRepository billName, IRecipientRepository recipient)
        {
            this.billRepository = bill;
            this.billNameRepository = billName;
            this.recipientRepository = recipient;
        }

        [HttpGet]
        public PartialViewResult AddBill()
        {
            CreationBillViewModel model = new CreationBillViewModel
            {
                Bills = billNameRepository.BillNames.Select(bn => new SelectBillItem
                {
                    Name = bn.Name,
                    Id = bn.BillNameID.ToString(),
                    Date = SetDate(bn.FirstPaymentDate, bn.PaymentsFrequency, bn.BillNameID)

                }).ToList(),

                Recipients = recipientRepository.Recipients.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.RecipientID.ToString()
                }).ToList()
            };
            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult AddBill(CreationBillViewModel model)
        {
            if (ModelState.IsValid)
            {
                Bill bill = new Bill
                {
                    BillNameID = model.SelectedBillId,
                    RecipientID = model.SelectedRecipientId,
                    Amount = model.Amount,
                    PaymentDate = DateTime.ParseExact(model.PaymentDate, "dd.MM.yyyy HH:mm",
                                           System.Globalization.CultureInfo.InvariantCulture),
                    RequiredDate = DateTime.ParseExact(model.RequiredDate, "dd.MM.yyyy",
                                           System.Globalization.CultureInfo.InvariantCulture),
                };

                billRepository.SaveBill(bill);
            }

            return RedirectToAction("Index", "Home");
        }


        public DateTime SetDate(DateTime firstPaymentDate, int paymentFerquency, int billNameId)
        {
            DateTime date;

            if (billRepository.Bills.Any(b => b.BillNameID == billNameId))
                date = billRepository.Bills.Last(b => b.BillNameID == billNameId).RequiredDate.AddDays(paymentFerquency);
            else
                date = firstPaymentDate.AddDays(paymentFerquency);
            return date;
        }
    }
}

WydatkiDomoweWeb.WebUI/Views/Bill/AddBill.cshtml
@model WydatkiDomoweWeb.WebUI.Models.CreationBillViewModel


@using (Html.BeginForm("AddBill", "Bill", FormMethod.Post, new { @class = "form-inline" }))
{
    <div class="form-group form-group-sm">
        @Html.DropDownListFor(m => m.SelectedBillId, new SelectList(Model.Bills, "Id", "Name"), "Wybierz rachunek", new { @class = "form-control", id = "selectBill" })
        @for (int i = 0; i < Model.Bills.Count(); i++)
        {
            @Html.HiddenFor(m => m.Bills[i].Name)
            @Html.HiddenFor(m => m.Bills[i].Id)
            @Html.HiddenFor(m => m.Bills[i].Date, new { id = Model.Bills[i].Id })
        }
    </div>
     <div class="form-group form-group-sm">
        @Html.DropDownListFor(m => m.SelectedRecipientId, new SelectList(Model.Recipients, "Value", "Text"), "Wybierz odbiorcę", new { @class = "form-control" })
        @for (int i = 0; i < Model.Recipients.Count(); i++)
        {
            @Html.HiddenFor(m => m.Recipients[i].Text)
            @Html.HiddenFor(m => m.Recipients[i].Value)
        }
    </div>
    <div class="form-group form-group-sm">
        @Html.TextBoxFor(m => m.Amount, "Kwota", new { @class = "form-control" })

    </div>
    <div style="position:relative" class="form-group form-group-sm">   
        @Html.TextBoxFor(m => m.PaymentDate, new { @class = "form-control", id = "datetimepicker", Value = "Data wpłaty" })  


    </div>
    <div class="form-group form-group-sm">
        @Html.TextBoxFor(m => m.RequiredDate, new { @class = "form-control", id = "requiredDate", Value = "Termin zapłaty" })
    </div>
    <div class="form-group form-group-sm">
        <input type="hidden" id="buttonvalue" />
        <input id="idbutton" class="btn btn-primary" type="submit" value="Dodaj nowy rachunek" />
    </div>
        
}

WydatkiDomoweWeb.WebUI/Views/Bill/List.cshtml
@using WydatkiDomoweWeb.Domain.Entities
@model WydatkiDomoweWeb.WebUI.Models.BillViewModel


@{
    ViewBag.Title = "Rachunki";
}

<div class="panel panel-default">
    <div class="panel panel-body">
        @Html.Action("Items", "CheckboxBills")
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th>Rachunek</th>
                <th>Odbiorca</th>
                <th>Cena</th>
                <th>Data wpłaty</th>
                <th>Termin zapłaty</th>
                <th>Akcja</th>
            </tr>
            @foreach (var b in Model.Bills)
            {
                <tr>
                    <td>@Html.DisplayFor(m => b.BillName)</td>
                    <td>@Html.DisplayFor(m => b.Recipient)</td>
                    <td>@Html.DisplayFor(m => b.Amount)</td>
                    <td>@Html.DisplayFor(m => b.PaymentDate)</td>
                    <td>@Html.DisplayFor(m => b.RequiredDate)</td>
                    <td>
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            <input class = "btn btn-default btn-xs" type="submit" value="Usuń" />
                        }
                    </td>
                </tr>
            }
        </table>
        <div class="btn-group pull-right">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
        </div>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("Dodaj nowy produkt", "Usuń", null, new { @class = "btn btn-default" })
    </div>
</div>