WydatkiDomoweWeb.WebUI/Models/CheckboxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WydatkiDomoweWeb.Domain.Abstract;

namespace WydatkiDomoweWeb.WebUI.Models
{
    public class CheckboxModel
    {
        public string Name { get; set; }
        public bool IsChecked { get; set; }
    }

    public class CheckboxViewModel
    {
        public List<CheckboxModel> Items { get; set; }

        public CheckboxViewModel()
        {
            Items = new List<CheckboxModel>();
        }
    }
}

WydatkiDomoweWeb.WebUI/Controllers/CrudBillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WydatkiDomoweWeb.WebUI.Models;
using WydatkiDomoweWeb.Domain.Abstract;
using WydatkiDomoweWeb.Domain.Entities;

namespace WydatkiDomoweWeb.WebUI.Controllers
{
    public class CrudBillController : Controller
    {
        private IBillRepository billRepository;
        private IBillNameRepository billNameRepository;
        private IRecipientRepository recipientRepository;

        public CrudBillController(IBillRepository bill, IBillNameRepository billName, IRecipientRepository recipient)
        {
            this.billRepository = bill;
            this.billNameRepository = billName;
            this.recipientRepository = recipient;
        }

        [HttpGet]
        public PartialViewResult AddBill()
        {
            CrudBillViewModel model = new CrudBillViewModel
            {
                Bills = billNameRepository.BillNames.Select(bn => new SelectBill
                {
                    Name = bn.Name,
                    Id = bn.BillNameID.ToString(),
                    Date = SetDate(bn.FirstPaymentDate, bn.PaymentsFrequency, bn.BillNameID)

                }).ToList(),

                Recipients = recipientRepository.Recipients.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.RecipientID.ToString()
                }).ToList()
            };

            return PartialView(model);
        }

        protected DateTime SetDate(DateTime firstPaymentDate, int paymentFerquency, int billNameId)
        {
            DateTime date;

            if (billRepository.Bills.Any(b => b.BillNameID == billNameId))
                date = billRepository.Bills.Last(b => b.BillNameID == billNameId).RequiredDate.AddDays(paymentFerquency);
            else
                date = firstPaymentDate.AddDays(paymentFerquency);

            return date;
        }

        [HttpPost]
        public RedirectToRouteResult AddBill(CrudBillViewModel model)
        {
            if (ModelState.IsValid)
                billRepository.AddBill(CreateBill(model));

            TempData["ChangedBills"] = string.Format("Zapisano rachunek: {0} ", model.Bills.Single(b => b.Id == model.SelectedBillNameId.ToString()).Name);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public PartialViewResult EditBill(int billId)
        {
            var billNameId = billRepository.Bills.Single(b => b.BillsID == billId).BillNameID;

            CrudBillViewModel model = new CrudBillViewModel
            {                
                BillId = billId,
                SelectedBillNameId = billNameId,
                BillName = billNameRepository.BillNames.Single(bn => bn.BillNameID == billNameId).Name,
                Amount = billRepository.Bills.Single(b => b.BillsID == billId).Amount,
                PaymentDate = billRepository.Bills.Single(b => b.BillsID == billId).PaymentDate.ToString("dd.MM.yyyy HH:mm"),
                RequiredDate = billRepository.Bills.Single(b => b.BillsID == billId).RequiredDate.ToString("dd.MM.yyyy"),
                Recipients = recipientRepository.Recipients.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.RecipientID.ToString()
                }).ToList()
            };

            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult EditBill(CrudBillViewModel model)
        {
            if (ModelState.IsValid)
                billRepository.UpdateBill(CreateBill(model));

            TempData["ChangedBills"] = string.Format("Zapisano zmiany w rachunku: {0} ", model.BillName);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public RedirectToRouteResult DeleteBill(int billId, string billName)
        {
            billRepository.DeleteBill(billId);
            TempData["ChangedBills"] = string.Format("Usunięto rachunek: {0} ", billName);

            return RedirectToAction("GetBill", "Home");
        }

        protected Bill CreateBill(CrudBillViewModel model)
        {
            Bill bill = new Bill
            {
                BillsID = model.BillId,
                BillNameID = model.SelectedBillNameId,
                RecipientID = model.SelectedRecipientId,
                Amount = model.Amount,
                PaymentDate = DateTime.ParseExact(model.PaymentDate, "dd.MM.yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture),
                RequiredDate = DateTime.ParseExact(model.RequiredDate, "dd.MM.yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture),
            };

            return bill;
        }
    }
}

WydatkiDomoweWeb.WebUI/Controllers/CrudBillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WydatkiDomoweWeb.WebUI.Models;
using WydatkiDomoweWeb.Domain.Abstract;
using WydatkiDomoweWeb.Domain.Entities;

namespace WydatkiDomoweWeb.WebUI.Controllers
{
    public class CrudBillsController : Controller
    {
        private IBillRepository billRepository;
        private IBillNameRepository billNameRepository;
        private IRecipientRepository recipientRepository;

        public CrudBillsController(IBillRepository bill, IBillNameRepository billName, IRecipientRepository recipient)
        {
            this.billRepository = bill;
            this.billNameRepository = billName;
            this.recipientRepository = recipient;
        }

        [HttpGet]
        public PartialViewResult AddBill()
        {
            CrudBillsViewModel model = new CrudBillsViewModel
            {
                Bills = billNameRepository.BillNames.Select(bn => new SelectBillName
                {
                    BillNameId = bn.BillNameID.ToString(),
                    Name = bn.Name,                    
                    RequiredDate = SetRequiredDate(bn.FirstPaymentDate, bn.PaymentsFrequency, bn.BillNameID)

                }).ToList(),

                Recipients = recipientRepository.Recipients.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.RecipientID.ToString()
                }).ToList()
            };

            return PartialView(model);
        }

        protected DateTime SetRequiredDate(DateTime firstPaymentDate, int paymentFerquency, int billNameId)
        {
            DateTime date;

            if (billRepository.Bills.Any(b => b.BillNameID == billNameId))
                date = billRepository.Bills.Last(b => b.BillNameID == billNameId).RequiredDate.AddDays(paymentFerquency);
            else
                date = firstPaymentDate;

            return date;
        }

        [HttpPost]
        public RedirectToRouteResult AddBill(CrudBillsViewModel model)
        {
            if (ModelState.IsValid)
            {
                billRepository.Add(CreateBill(model));
                TempData["ChangedBill"] = string.Format("Zapisano rachunek: {0} ", model.Bills.Single(b => b.BillNameId == model.SelectedBillNameId.ToString()).Name);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public PartialViewResult EditBill(int billId)
        {
            int billNameId = billRepository.Bills.Single(b => b.BillsID == billId).BillNameID;

            CrudBillsViewModel model = new CrudBillsViewModel
            {                
                BillId = billId,
                SelectedBillNameId = billNameId,
                BillName = billNameRepository.BillNames.Single(bn => bn.BillNameID == billNameId).Name,
                Amount = billRepository.Bills.Single(b => b.BillsID == billId).Amount,
                PaymentDate = billRepository.Bills.Single(b => b.BillsID == billId).PaymentDate.ToString("dd.MM.yyyy"),
                RequiredDate = billRepository.Bills.Single(b => b.BillsID == billId).RequiredDate.ToString("dd.MM.yyyy"),
                Recipients = recipientRepository.Recipients.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.RecipientID.ToString()
                }).ToList()
            };

            return PartialView(model);
        }

        [HttpPost]
        public RedirectToRouteResult EditBill(CrudBillsViewModel model)
        {
            if (ModelState.IsValid)
            {
                billRepository.Update(CreateBill(model));
                TempData["ChangedBill"] = string.Format("Zapisano zmiany w rachunku: {0} ", model.BillName);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public RedirectToRouteResult DeleteBill(int billId, string billName)
        {
            billRepository.Delete(billId);
            TempData["ChangedBill"] = string.Format("Usunięto rachunek: {0} ", billName);

            return RedirectToAction("GetBills", "Home");
        }

        protected Bill CreateBill(CrudBillsViewModel model)
        {
            Bill bill = new Bill
            {
                BillsID = model.BillId,
                BillNameID = model.SelectedBillNameId,
                RecipientID = model.SelectedRecipientId,
                Amount = model.Amount,
                PaymentDate = DateTime.ParseExact(model.PaymentDate, "dd.MM.yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture),
                RequiredDate = DateTime.ParseExact(model.RequiredDate, "dd.MM.yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture),
            };

            return bill;
        }
    }
}

WydatkiDomoweWeb.WebUI/Controllers/HomeController.cs
using WydatkiDomoweWeb.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WydatkiDomoweWeb.Domain.Abstract;
using WydatkiDomoweWeb.WebUI.Infrastructure.Filters;

namespace WydatkiDomoweWeb.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBillRepository billRepository;
        private IBillNameRepository billNameRepository;
        private IRecipientRepository recipientRepository;

        public int PageSize = 10;

        public HomeController(IBillRepository bill, IBillNameRepository billName, IRecipientRepository recipient)
        {
            this.billRepository = bill;
            this.billNameRepository = billName;
            this.recipientRepository = recipient;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult GetBills(FilterBillsViewModel filterModel, int page = 1)
        {
            IEnumerable<BillViewModel> bills = (from b in billRepository.Bills
                         join bn in billNameRepository.BillNames
                            on b.BillNameID equals bn.BillNameID
                         join r in recipientRepository.Recipients
                            on b.RecipientID equals r.RecipientID
                         select new BillViewModel
                         {
                             BillId = b.BillsID,
                             BillName = bn.Name,
                             Recipient = r.Name,
                             Amount = b.Amount,
                             PaymentDate = b.PaymentDate,
                             RequiredDate = b.RequiredDate
                         }).FilterByCheckbox(filterModel).FilterByDateRange(filterModel);

            BillsViewModel model = new BillsViewModel
            {
                Bills = bills.OrderByDescending(b => b.PaymentDate).Skip((page - 1) * PageSize).Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = bills.Count()
                }
            };

            return PartialView(model);
        }

        [HttpGet]
        public PartialViewResult Filter(FilterBillsViewModel filterModel)
        {
            filterModel.CheckboxItems = (from bn in billNameRepository.BillNames
                                         select new CheckboxModel
                                         {
                                             Name = bn.Name,
                                             IsChecked = true
                                         }).ToList();

            if (billRepository.Bills.Count() != 0)
            {
                filterModel.MinDate = billRepository.Bills.OrderBy(b => b.PaymentDate).First().PaymentDate.ToString("dd.MM.yyyy");
                filterModel.MaxDate = billRepository.Bills.OrderBy(b => b.PaymentDate).Last().PaymentDate.ToString("dd.MM.yyyy");
            }
            
            return PartialView(filterModel);
        }

        [HttpPost]
        public RedirectToRouteResult FilterPost(FilterBillsViewModel filterPostModel)
        {
            return RedirectToAction("GetBills");
        }
    }
}

WydatkiDomoweWeb.WebUI/Views/Home/Checkbox.cshtml
@using WydatkiDomoweWeb.WebUI.Models
@model List<CheckboxModel>


@using (Ajax.BeginForm("Checkbox", "Home", new AjaxOptions { UpdateTargetId = "homeBillTable"}, new { @class = "form" }))
{
    for (int i = 0; i < Model.Count(); i++)
    {
        <label class="checkbox-inline">
            @Html.CheckBoxFor(m => m[i].IsChecked)
            @Html.HiddenFor(m => m[i].Name)
            @Html.DisplayFor(m => m[i].Name)
        </label>
    }
        
    <input class="btn btn-primary" type="submit" value="Filtruj" />
}

WydatkiDomoweWeb.WebUI/Views/Home/DeleteBillDialog.cshtml
@model WydatkiDomoweWeb.WebUI.Models.BillViewModel

<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h3 class="modal-title"> Usuwanie rachunku</h3>
        </div>
        <div class="modal-body">
            <h5>Chcesz usunąć rachunek "@Model.BillName"?</h5>
        </div>
        <div class="modal-footer">
            @using (Ajax.BeginForm("DeleteBill", "CrudBills", null, new AjaxOptions { UpdateTargetId = "billsTable", OnSuccess = "hideModal()" }, new { @class = "form-group" }))
            {
                @Html.Hidden("BillId", Model.BillId)
                @Html.Hidden("BillName", Model.BillName)
                <input class="btn btn-primary" type="submit" value="Usuń" />
            }
            <button type="button" class="btn btn-default" data-dismiss="modal"> Anuluj</button>
        </div>
    </div>
</div>

WydatkiDomoweWeb.WebUI/Views/Home/Filter.cshtml
@model WydatkiDomoweWeb.WebUI.Models.FilterBillsViewModel


@using (Ajax.BeginForm("FilterPost", "Home", new AjaxOptions { UpdateTargetId = "billsTable"}, new { @class = "form-inline" }))
{
    for (int i = 0; i < Model.CheckboxItems.Count(); i++)
    {
        <label class="checkbox-inline">
            @Html.CheckBoxFor(m => m.CheckboxItems[i].IsChecked)
            @Html.HiddenFor(m => m.CheckboxItems[i].Name)
            @Html.DisplayFor(m => m.CheckboxItems[i].Name)
        </label>
    }
    
    <div style="position: relative" class="form-group">
        @Html.TextBoxFor(m => m.MinDate, new { @class = "form-control form-centered", id = "datetimepickerMin", Value = @Model.MinDate })
         @Html.ValidationMessageFor(m => m.MinDate)
    </div>
    <div style="position: relative" class="form-group">
        @Html.TextBoxFor(m => m.MaxDate, new { @class = "form-control form-centered", id = "datetimepickerMax", Value = @Model.MaxDate })
        @Html.ValidationMessageFor(m => m.MaxDate)
    </div>
        
    <input class="btn btn-primary" type="submit" value="Filtruj" />
}

WydatkiDomoweWeb.WebUI/Views/Home/GetBill.cshtml
@model WydatkiDomoweWeb.WebUI.Models.BillViewModel

@if (TempData["ChangedBills"] != null) 
{
    <div class="alert alert-success">@TempData["ChangedBills"]</div>
}
 <table class="table table-striped table-condensed table-bordered table-getbill">
    <tr>
        <th class="col-md-2">Rachunek</th>
        <th class="col-md-2">Odbiorca</th>
        <th class="col-md-1">Cena</th>
        <th class="col-md-2">Data wpłaty</th>
        <th class="col-md-2">Termin zapłaty</th>
        <th class="col-md-1">Akcja</th>
    </tr>


    @foreach (var bills in Model.Bills)
    {
        <tr>
            <td>@Html.DisplayFor(m => bills.BillName)</td>
            <td>@Html.DisplayFor(m => bills.Recipient)</td>
            <td>@Html.DisplayFor(m => bills.Amount)</td>
            <td>@Html.DisplayFor(m => bills.PaymentDate)</td>
            <td>@Html.DisplayFor(m => bills.RequiredDate)</td>
            <td class="form-inline">                    
                @using (Ajax.BeginForm("EditBill", "CrudBill", null, new AjaxOptions { UpdateTargetId = "homeEditBill", HttpMethod = "Get", OnSuccess = "configureEditBill" }, new { @class = "form-group" }))
                {
                    @Html.Hidden("BillId", bills.Id)
                    <input class="btn btn-default btn-xs" type="submit" value="Edytuj"/>
                }
                
                @using (Ajax.BeginForm("DeleteBill", "CrudBill", null, new AjaxOptions { Confirm = "Chcesz usunąć element", UpdateTargetId = "homeBillTable"}, new { @class = "form-group" }))
                {
                    @Html.Hidden("BillId", bills.Id)
                    @Html.Hidden("BillName", bills.BillName)
                    <input class="btn btn-default btn-xs" type="submit" value="Usuń"/>
                }
            </td>
        </tr>
    }
</table>

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("GetBill", new { page = x }), new AjaxOptions { UpdateTargetId = "homeBillTable" })
</div>

WydatkiDomoweWeb.WebUI/Views/Home/GetBills.cshtml
@model WydatkiDomoweWeb.WebUI.Models.BillsViewModel

@if (TempData["ChangedBill"] != null) 
{
    <div class="alert alert-success">@TempData["ChangedBill"]</div>
}

 <table class="table table-striped table-condensed table-bordered table-getItem">
    <tr>
        <th class="col-md-2">Rachunek</th>
        <th class="col-md-2">Odbiorca</th>
        <th class="col-md-1">Cena</th>
        <th class="col-md-2">Data wpłaty</th>
        <th class="col-md-2">Termin zapłaty</th>
        <th class="col-md-1">Akcja</th>
    </tr>


    @foreach (var bill in Model.Bills)
    {
        <tr>
            <td>@Html.DisplayFor(m => bill.BillName)</td>
            <td>@Html.DisplayFor(m => bill.Recipient)</td>
            <td>@Html.DisplayFor(m => bill.Amount)</td>
            <td>@Html.DisplayFor(m => bill.PaymentDate)</td>
            <td>@Html.DisplayFor(m => bill.RequiredDate)</td>
            <td class="form-inline">                    
                @using (Ajax.BeginForm("EditBill", "CrudBills", null, new AjaxOptions { UpdateTargetId = "addItem", HttpMethod = "Get", OnSuccess = "setDefaultDateTimePicker('paymentDate')" }, new { @class = "form-group" }))
                {
                    @Html.Hidden("BillId", bill.BillId)
                    <input class="btn btn-default btn-xs" type="submit" value="Edytuj" />
                }
                <button class="btn btn-default btn-xs" data-toggle="modal" data-target="#@("modal" + bill.BillId)">Usuń</button>                
                <div id="@("modal" + bill.BillId)" class="modal fade" role="dialog">                
                    @Html.Partial("DeleteBillDialog", bill)
                </div>
            </td>
        </tr>
    }
 </table>
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("GetBills", new { page = x }), new AjaxOptions { UpdateTargetId = "billsTable" })
</div>

WydatkiDomoweWeb.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Główna";
}

<div id="bills" class="panel panel-default">
    <div class="panel-body">
        @Html.Action("Filter")
    </div>
    <div class="panel-body" id="billsTable">
        @Html.Action("GetBills")
    </div>
    <div class="panel-footer">
        <div  id="addItem">
            @Ajax.ActionLink("Dodaj nowy rachunek", "AddBill", "CrudBills", null, new AjaxOptions() { UpdateTargetId = "addItem", HttpMethod = "Get", OnSuccess = "configureAddBill" }, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>